### ISSUE TITLE
Invalid PyPI auth in CI

### ISSUE THREAD

**Issue by hukkin** [executablebooks/mdformat-tables#14]
GitHub CI failed to publish v0.4.1. 

Here's the error from `flit publish`
```
flit publish
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    FLIT_USERNAME: __token__
    FLIT_PASSWORD: ***
Fetching list of valid trove classifiers               I-flit.validate
Found 16 files tracked in git                             I-flit.sdist
Writing generated setup.py                                I-flit.sdist
Built sdist: dist/mdformat_tables-0.4.1.tar.gz       I-flit_core.sdist
Copying package file(s) from /tmp/tmpok5jp252/mdformat_tables-0.4.1/mdformat_tables  I-flit_core.wheel
Writing metadata files                               I-flit_core.wheel
Writing the record of files                          I-flit_core.wheel
Built wheel: dist/mdformat_tables-0.4.1-py3-none-any.whl  I-flit_core.wheel
Using repository at https://upload.pypi.org/legacy/      I-flit.upload
Uploading dist/mdformat_tables-0.4.1-py3-none-any.whl... I-flit.upload
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/bin/flit", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/flit/__init__.py", line 164, in main
    gen_setup_py=args.setup_py)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/flit/upload.py", line 260, in main
    do_upload(built.wheel.file, built.wheel.builder.metadata, repo_name)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/flit/upload.py", line 243, in do_upload
    upload_file(file, metadata, repo)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/flit/upload.py", line 236, in upload_file
    resp.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information. for url: https://upload.pypi.org/legacy/
Error: Process completed with exit code 1.

**Comment by KyleKing** [comment]
Appears to be working again!

https://github.com/executablebooks/mdformat-tables/actions/runs/10533763354
